### ISSUE TITLE
API v2 is down #5791

### ISSUE THREAD

**Issue by mathieudebrito** [openfoodfacts/openfoodfacts-upptime#5792]
Hello guys, 

This message is related to API v2 is down #5791 

I think I might be the one who made the API down.
I'm trying to call the OpenFoodFacts API as an autocomplete in my KMP app.

The api call that may have put down the api is : 
https://world.openfoodfacts.org/api/v2/search?product_name=to&fields=code,product_name

I was searching for a tomate (tomatoe in french).

please tell me if I misused the API.
Also, I wanted to add an http header so that you can contact me just in case (as mentionned in the docs) but I did not find what header specifically you are looking for.

Best regards,

**Comment by CharlesNepote** [comment]
Sorry for the late reply @mathieudebrito.

As you can see, the issue was resolved 6 minutes later: https://github.com/openfoodfacts/openfoodfacts-upptime/issues/5791#issuecomment-2423307714

> I'm trying to call the OpenFoodFacts API as an autocomplete in my KMP app.
>
> The api call that may have put down the api is :
> https://world.openfoodfacts.org/api/v2/search?product_name=to&fields=code,product_name

**You must not use the API for such a need**. We need to take care of the resource and we have rate limits, see here: https://openfoodfacts.github.io/openfoodfacts-server/api/#rate-limits
=> **10 req/min** for all search queries (GET /api/v*/search or GET /cgi/search.pl requests)

If you want to build an autocomplete, please download the data and use it locally. There are many ways to reuse data, see: https://wiki.openfoodfacts.org/Reusing_Open_Food_Facts_Data
If you only need code and product name, you can build your own export thanks to Mirabelle for example (see documentation on previous link).

> Also, I wanted to add an http header so that you can contact me just in case (as mentionned in the docs) but I did not find what header specifically you are looking for.

You should send a `User-Agent` header, see: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent
We describe what we're waiting for here: https://openfoodfacts.github.io/openfoodfacts-server/api/#authentication
